# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 543)
        MainWindow.setMinimumSize(QtCore.QSize(0, 535))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_stock = QtWidgets.QWidget()
        self.tab_stock.setObjectName("tab_stock")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_stock)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_stock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_stock = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_stock.setObjectName("lineEdit_stock")
        self.horizontalLayout_3.addWidget(self.lineEdit_stock)
        self.pushButton_add_stock = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_add_stock.setObjectName("pushButton_add_stock")
        self.horizontalLayout_3.addWidget(self.pushButton_add_stock)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tableView_selected_stock = QtWidgets.QTableView(self.groupBox_3)
        self.tableView_selected_stock.setSortingEnabled(True)
        self.tableView_selected_stock.setObjectName("tableView_selected_stock")
        self.verticalLayout_6.addWidget(self.tableView_selected_stock)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_delete_stock = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_delete_stock.setObjectName("pushButton_delete_stock")
        self.horizontalLayout_4.addWidget(self.pushButton_delete_stock)
        self.pushButton_clearall_stock = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_clearall_stock.setObjectName("pushButton_clearall_stock")
        self.horizontalLayout_4.addWidget(self.pushButton_clearall_stock)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_stock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget_hq_header_left = QtWidgets.QListWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_hq_header_left.sizePolicy().hasHeightForWidth())
        self.listWidget_hq_header_left.setSizePolicy(sizePolicy)
        self.listWidget_hq_header_left.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listWidget_hq_header_left.setObjectName("listWidget_hq_header_left")
        self.horizontalLayout_5.addWidget(self.listWidget_hq_header_left)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.listWidget_hq_header_right = QtWidgets.QListWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_hq_header_right.sizePolicy().hasHeightForWidth())
        self.listWidget_hq_header_right.setSizePolicy(sizePolicy)
        self.listWidget_hq_header_right.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listWidget_hq_header_right.setObjectName("listWidget_hq_header_right")
        self.horizontalLayout_5.addWidget(self.listWidget_hq_header_right)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_stock, "")
        self.tab_hq = QtWidgets.QWidget()
        self.tab_hq.setObjectName("tab_hq")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_hq)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView_hq = QtWidgets.QTableView(self.tab_hq)
        self.tableView_hq.setSortingEnabled(True)
        self.tableView_hq.setObjectName("tableView_hq")
        self.horizontalLayout.addWidget(self.tableView_hq)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_hq_start_stop = QtWidgets.QPushButton(self.tab_hq)
        self.pushButton_hq_start_stop.setObjectName("pushButton_hq_start_stop")
        self.verticalLayout.addWidget(self.pushButton_hq_start_stop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_hq, "")
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_setting)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_setting)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_url = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_url)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_sh = QtWidgets.QLabel(self.groupBox)
        self.label_sh.setText("")
        self.label_sh.setObjectName("label_sh")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_sh)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_sz = QtWidgets.QLabel(self.groupBox)
        self.label_sz.setText("")
        self.label_sz.setObjectName("label_sz")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_sz)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_setting)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_log_to_file = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_log_to_file.setObjectName("checkBox_log_to_file")
        self.verticalLayout_11.addWidget(self.checkBox_log_to_file)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_log = QtWidgets.QLabel(self.groupBox_2)
        self.label_log.setObjectName("label_log")
        self.horizontalLayout_13.addWidget(self.label_log)
        self.lineEdit_logfile = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_logfile.setObjectName("lineEdit_logfile")
        self.horizontalLayout_13.addWidget(self.lineEdit_logfile)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_setting, "")
        self.tab_about = QtWidgets.QWidget()
        self.tab_about.setObjectName("tab_about")
        self.tabWidget.addTab(self.tab_about, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 753, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "加入自选股"))
        self.pushButton_add_stock.setText(_translate("MainWindow", "加入"))
        self.pushButton_delete_stock.setText(_translate("MainWindow", "删除"))
        self.pushButton_clearall_stock.setText(_translate("MainWindow", "全部清除"))
        self.groupBox_4.setTitle(_translate("MainWindow", "行情列"))
        self.label_3.setText(_translate("MainWindow", "<==>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stock), _translate("MainWindow", "自选股"))
        self.pushButton_hq_start_stop.setText(_translate("MainWindow", "开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hq), _translate("MainWindow", "行情"))
        self.groupBox.setTitle(_translate("MainWindow", "Stcok HQ"))
        self.label.setText(_translate("MainWindow", "HQ url:"))
        self.lineEdit_url.setText(_translate("MainWindow", "http://127.0.0.1/hq"))
        self.label_2.setText(_translate("MainWindow", "上证A股："))
        self.label_5.setText(_translate("MainWindow", "深证A股："))
        self.groupBox_2.setTitle(_translate("MainWindow", "Log"))
        self.checkBox_log_to_file.setText(_translate("MainWindow", "记录到文件"))
        self.label_log.setText(_translate("MainWindow", "日志文件:"))
        self.lineEdit_logfile.setText(_translate("MainWindow", "stockhq.log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), _translate("MainWindow", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), _translate("MainWindow", "关于"))

