#!/usr/bin/env python
# -*- encoding:utf-8 -*-


FinanceModelDesc = dict([
    ('Main', u'主要指标'),
    ('Debt', u'资产负载表'),
    ('Benefit', u'利润表'),
    ('Cash', u'现金流量表'),
])


Main_field = [
    ['date', 'DATE', u'日期', {}, None],
    ['jbmgsy', 'REAL', u'基本每股收益', 'chart_line_value', u'元'],
    ['jlr', 'REAL', u'净利润', 'chart_line_value', u'万元'],
    ['jlrtbzzl', 'REAL', u'净利润同比增长率', 'chart_line_ratio', '%'],
    ['yyzsr', 'REAL', u'营业总收入', 'chart_line_value', u'万元'],
    ['yyzsrtbzzl', 'REAL', u'营业总收入同比增长率', 'chart_line_ratio', '%'],
    ['mgjzc', 'REAL', u'每股净资产', 'chart_line_value', u'元'],
    ['jzcsyl', 'REAL', u'净资产收益率', 'chart_line_ratio', '%'],
    ['jzcsyltb', 'REAL', u'净资产收益率-摊薄', 'chart_line_ratio', '%'],
    ['zcfzbl', 'REAL', u'资产负债比率', 'chart_line_ratio', '%'],
    ['mgzbgjj', 'REAL', u'每股资本公积金', 'chart_line_value', u'元'],
    ['mgwfplr', 'REAL', u'每股未分配利润', 'chart_line_value', u'元'],
    ['mgjyxjl', 'REAL', u'每股经营现金流', 'chart_line_value', u'元'],
    ['xsmll', 'REAL', u'销售毛利率', 'chart_line_ratio', '%'],
    ['chzzl', 'REAL', u'存货周转率', 'chart_line_ratio', None],
    ['kfjlr', 'REAL', u'扣非净利润', 'chart_line_value', u'万元'],
]
Benefit_field = [
    ['date', 'DATE', u'日期', {}, None],
    ['jlr', 'REAL', u'净利润', 'chart_line_value', u'万元'],
    ['yyzsr', 'REAL', u'营业总收入', 'chart_line_value', u'万元'],
    ['yysr', 'REAL', u'营业收入', 'chart_line_value', u'万元'],
    ['yyzcb', 'REAL', u'营业总成本', 'chart_line_value', u'万元'],
    ['yycb', 'REAL', u'营业成本', 'chart_line_value', u'万元'],
    ['yylr', 'REAL', u'营业利润', 'chart_line_value', u'万元'],
    ['tzsy', 'REAL', u'投资收益', 'chart_line_value', u'万元'],
    ['qzlyqyhhyqydtzsy', 'REAL', u'其中：联营企业和合营企业的投资收益', 'chart_line_value', u'万元'],
    ['zcjzss', 'REAL', u'资产减值损失', 'chart_line_value', u'万元'],
    ['glfy', 'REAL', u'管理费用', 'chart_line_value', u'万元'],
    ['xsfy', 'REAL', u'销售费用', 'chart_line_value', u'万元'],
    ['cwfy', 'REAL', u'财务费用', 'chart_line_value', u'万元'],
    ['yywsr', 'REAL', u'营业外收入', 'chart_line_value', u'万元'],
    ['yywzc', 'REAL', u'营业外支出', 'chart_line_value', u'万元'],
    ['yysjjfj', 'REAL', u'营业税金及附加', 'chart_line_value', u'万元'],
    ['lrze', 'REAL', u'利润总额', 'chart_line_value', u'万元'],
    ['sds', 'REAL', u'所得税', 'chart_line_value', u'万元'],
    ['qtzhsy', 'REAL', u'其他综合收益', 'chart_line_value', u'万元'],
    ['zhsyze', 'REAL', u'综合收益总额', 'chart_line_value', u'万元'],
    ['gsymgsgddzhsyze', 'REAL', u'归属于母公司股东的综合收益总额', 'chart_line_value', u'万元'],
    ['gsyssgddzhsyze', 'REAL', u'归属于少数股东的综合收益总额', 'chart_line_value', u'万元'],
    ['lxsr', 'REAL', u'利息收入', 'chart_line_value', u'万元'],
    ['lxzc', 'REAL', u'利息支出', 'chart_line_value', u'万元'],
    ['lxjsr', 'REAL', u'利息净收入', 'chart_line_value', u'万元'],
    ['sxfjyjjsr', 'REAL', u'手续费及佣金净收入', 'chart_line_value', u'万元'],
    ['hdsy', 'REAL', u'汇兑收益', 'chart_line_value', u'万元'],
    ['gyjzbdsy', 'REAL', u'公允价值变动收益', 'chart_line_value', u'万元'],
    ['yzbf', 'REAL', u'已赚保费', 'chart_line_value', u'万元'],
    ['bxyfsr', 'REAL', u'保险业务收入', 'chart_line_value', u'万元'],
    ['tqbxzyzbj', 'REAL', u'提取保险责任准备金', 'chart_line_value', u'万元'],
    ['pfzc', 'REAL', u'赔付支出', 'chart_line_value', u'万元'],
    ['tbj', 'REAL', u'退保金', 'chart_line_value', u'万元'],
    ['fbfy', 'REAL', u'分保费用', 'chart_line_value', u'万元'],
    ['bdhlzc', 'REAL', u'保单红利支出', 'chart_line_value', u'万元'],
    ['dlmmzqyfjsr', 'REAL', u'代理买卖证券业务净收入', 'chart_line_value', u'万元'],
    ['zqcxyfjsr', 'REAL', u'证券承销业务净收入', 'chart_line_value', u'万元'],
    ['stkhzcglywjsr', 'REAL', u'受托客户资产管理业务净收入', 'chart_line_value', u'万元'],
    ['kfjlr', 'REAL', u'扣非净利润', 'chart_line_value', u'万元'],
    ['ywjglf', 'REAL', u'业务及管理费', 'chart_line_value', u'万元'],
]
Cash_field = [
    ['date', 'DATE', u'日期', {}, None],
    ['xssptglwsddxj', 'REAL', u'销售商品、提供劳务收到的现金', 'chart_line_value', u'万元'],
    ['sddsfyfh', 'REAL', u'收到的税费与返还', 'chart_line_value', u'万元'],
    ['zfdgxsf', 'REAL', u'支付的各项税费', 'chart_line_value', u'万元'],
    ['zfgzgyjwzgzfdxj', 'REAL', u'支付给职工以及为职工支付的现金', 'chart_line_value', u'万元'],
    ['jyxjlr', 'REAL', u'经营现金流入', 'chart_line_value', u'万元'],
    ['jyxjlc', 'REAL', u'经营现金流出', 'chart_line_value', u'万元'],
    ['jyxjllje', 'REAL', u'经营现金流量净额', 'chart_line_value', u'万元'],
    ['wzgdzcwxzcdxj', 'REAL', u'处置固定资产、无形资产的现金', 'chart_line_value', u'万元'],
    ['czzgsjqtsddxj', 'REAL', u'处置子公司及其他收到的现金', 'chart_line_value', u'万元'],
    ['gzgdzchqtzfdxj', 'REAL', u'购建固定资产和其他支付的现金', 'chart_line_value', u'万元'],
    ['tzzfdxj', 'REAL', u'投资支付的现金', 'chart_line_value', u'万元'],
    ['zdzgsxjje', 'REAL', u'取得子公司现金净额', 'chart_line_value', u'万元'],
    ['zfqtytzdxj', 'REAL', u'支付其他与投资的现金', 'chart_line_value', u'万元'],
    ['tzxjlr', 'REAL', u'投资现金流入', 'chart_line_value', u'万元'],
    ['tzxjlc', 'REAL', u'投资现金流出', 'chart_line_value', u'万元'],
    ['tzxjllje', 'REAL', u'投资现金流量净额', 'chart_line_value', u'万元'],
    ['xstzsdxj', 'REAL', u'吸收投资收到现金', 'chart_line_value', u'万元'],
    ['qzzgsxsxj', 'REAL', u'其中子公司吸收现金', 'chart_line_value', u'万元'],
    ['qdjkdxj', 'REAL', u'取得借款的现金', 'chart_line_value', u'万元'],
    ['sdqtyczdxj', 'REAL', u'收到其他与筹资的现金', 'chart_line_value', u'万元'],
    ['chzfzfxj', 'REAL', u'偿还债务支付现金', 'chart_line_value', u'万元'],
    ['fpgllrhcflzzfdxj', 'REAL', u'分配股利、利润或偿付利息支付的现金', 'chart_line_value', u'万元'],
    ['qzzgszfgl', 'REAL', u'其中子公司支付股利', 'chart_line_value', u'万元'],
    ['zfqtyczdxj', 'REAL', u'支付其他与筹资的现金', 'chart_line_value', u'万元'],
    ['czxjlr', 'REAL', u'筹资现金流入', 'chart_line_value', u'万元'],
    ['czxjlc', 'REAL', u'筹资现金流出', 'chart_line_value', u'万元'],
    ['czxjllje', 'REAL', u'筹资现金流量净额', 'chart_line_value', u'万元'],
    ['hlbddxjdyx', 'REAL', u'汇率变动对现金的影响', 'chart_line_value', u'万元'],
    ['xjjxjdjwjzje', 'REAL', u'现金及现金等价物净增加额', 'chart_line_value', u'万元'],
    ['khckhtycfkxjzje', 'REAL', u'客户存款和同业存放款项净增加额', 'chart_line_value', u'万元'],
    ['khdkjdkjzje', 'REAL', u'客户贷款及垫款净增加额', 'chart_line_value', u'万元'],
    ['sdybxhtbfqddxj', 'REAL', u'收到原保险合同保费取得的现金', 'chart_line_value', u'万元'],
    ['bhcjjtzkjzje', 'REAL', u'保户储金及投资款净增加额', 'chart_line_value', u'万元'],
    ['zfybxhtpfkxdxj', 'REAL', u'支付原保险合同赔付款项的现金', 'chart_line_value', u'万元'],
    ['zfbdhldxj', 'REAL', u'支付保单红利的现金', 'chart_line_value', u'万元'],
    ['qdtzsysddxj', 'REAL', u'取得投资收益收到的现金', 'chart_line_value', u'万元'],
    ['shtzsddxj', 'REAL', u'收回投资收到的现金', 'chart_line_value', u'万元'],

]
Debt_field = [
    ['date', 'DATE', u'日期', {}, None],
    ['hbzj', 'REAL', u'货币资金', 'chart_line_value', u'万元'],
    ['jyxjrzc', 'REAL', u'交易性金融资产', 'chart_line_value', u'万元'],
    ['yspj', 'REAL', u'应收票据', 'chart_line_value', u'万元'],
    ['yszk', 'REAL', u'应收账款', 'chart_line_value', u'万元'],
    ['yfzk', 'REAL', u'预付账款', 'chart_line_value', u'万元'],
    ['ysgl', 'REAL', u'应收股利', 'chart_line_value', u'万元'],
    ['qtysk', 'REAL', u'其他应收款', 'chart_line_value', u'万元'],
    ['ch', 'REAL', u'存货', 'chart_line_value', u'万元'],
    ['ynndqdfldzc', 'REAL', u'一年内到期的非流动资产', 'chart_line_value', u'万元'],
    ['qtldzc', 'REAL', u'其他流动资产', 'chart_line_value', u'万元'],
    ['ldzchj', 'REAL', u'流动资产合计', 'chart_line_value', u'万元'],
    ['kgcsjrzc', 'REAL', u'可供出售金融资产', 'chart_line_value', u'万元'],
    ['cyzdqtz', 'REAL', u'持有至到期投资', 'chart_line_value', u'万元'],
    ['cqysk', 'REAL', u'长期应收款', 'chart_line_value', u'万元'],
    ['cqgqtz', 'REAL', u'长期股权投资', 'chart_line_value', u'万元'],
    ['tzxfdc', 'REAL', u'投资性房地产', 'chart_line_value', u'万元'],
    ['gdzc', 'REAL', u'固定资产', 'chart_line_value', u'万元'],
    ['zjgc', 'REAL', u'在建工程', 'chart_line_value', u'万元'],
    ['gdzcql', 'REAL', u'固定资产清理', 'chart_line_value', u'万元'],
    ['wxzc', 'REAL', u'无形资产', 'chart_line_value', u'万元'],
    ['sy', 'REAL', u'商誉', 'chart_line_value', u'万元'],
    ['cqdtfy', 'REAL', u'长期待摊费用', 'chart_line_value', u'万元'],
    ['dysdszc', 'REAL', u'递延所得税资产', 'chart_line_value', u'万元'],
    ['fldzchj', 'REAL', u'非流动资产合计', 'chart_line_value', u'万元'],
    ['dqjk', 'REAL', u'短期借款', 'chart_line_value', u'万元'],
    ['jyxjrfz', 'REAL', u'交易性金融负债', 'chart_line_value', u'万元'],
    ['yfpj', 'REAL', u'应付票据', 'chart_line_value', u'万元'],
    ['jfzk', 'REAL', u'应付账款', 'chart_line_value', u'万元'],
    ['y_szk', 'REAL', u'预收账款', 'chart_line_value', u'万元'],
    ['yjsf', 'REAL', u'应交税费', 'chart_line_value', u'万元'],
    ['yflx', 'REAL', u'应付利息', 'chart_line_value', u'万元'],
    ['yfgl', 'REAL', u'应付股利', 'chart_line_value', u'万元'],
    ['qtyfk', 'REAL', u'其他应付款', 'chart_line_value', u'万元'],
    ['ynndqdfldfz', 'REAL', u'一年内到期的非流动负债', 'chart_line_value', u'万元'],
    ['qtldfz', 'REAL', u'其他流动负债', 'chart_line_value', u'万元'],
    ['ldfzhj', 'REAL', u'流动负债合计', 'chart_line_value', u'万元'],
    ['cqjk', 'REAL', u'长期借款', 'chart_line_value', u'万元'],
    ['yfzq', 'REAL', u'应付债券', 'chart_line_value', u'万元'],
    ['cqyfk', 'REAL', u'长期应付款', 'chart_line_value', u'万元'],
    ['zxyfk', 'REAL', u'专项应付款', 'chart_line_value', u'万元'],
    ['yjfz', 'REAL', u'预计负债', 'chart_line_value', u'万元'],
    ['dysdsfz', 'REAL', u'递延所得税负债', 'chart_line_value', u'万元'],
    ['qtfldfz', 'REAL', u'其他非流动负债', 'chart_line_value', u'万元'],
    ['fldfzhj', 'REAL', u'非流动负债合计', 'chart_line_value', u'万元'],
    ['fzhj', 'REAL', u'负债合计', 'chart_line_value', u'万元'],
    ['gb', 'REAL', u'股本', 'chart_line_value', u'万股'],
    ['zbgjj', 'REAL', u'资本公积金', 'chart_line_value', u'万元'],
    ['yygjj', 'REAL', u'盈余公积金', 'chart_line_value', u'万元'],
    ['wfplr', 'REAL', u'未分配利润', 'chart_line_value', u'万元'],
    ['wbbbzsce', 'REAL', u'外币报表折算差额', 'chart_line_value', u'万元'],
    ['gsymgsgdqyhj', 'REAL', u'归属于母公司股东权益合计', 'chart_line_value', u'万元'],
    ['ssgdqy', 'REAL', u'少数股东权益', 'chart_line_value', u'万元'],
    ['gdqyhj', 'REAL', u'股东权益合计', 'chart_line_value', u'万元'],
    ['fzhgdqyzj', 'REAL', u'负债和股东权益总计', 'chart_line_value', u'万元'],
    ['yslx', 'REAL', u'应收利息', 'chart_line_value', u'万元'],
    ['jkcg', 'REAL', u'减:库存股', 'chart_line_value', u'万元'],
    ['gcwz', 'REAL', u'工程物资', 'chart_line_value', u'万元'],
    ['scxswzc', 'REAL', u'生产性生物资产', 'chart_line_value', u'万元'],
    ['zxcb', 'REAL', u'专项储备', 'chart_line_value', u'万元'],
    ['xjjcfzyyhkx', 'REAL', u'现金及存放中央银行款项', 'chart_line_value', u'万元'],
    ['cftykx', 'REAL', u'存放同业款项', 'chart_line_value', u'万元'],
    ['ffdkjdk', 'REAL', u'发放贷款及垫款', 'chart_line_value', u'万元'],
    ['xzyyhjk', 'REAL', u'向中央银行借款', 'chart_line_value', u'万元'],
    ['tyjqtjrjgcfkx', 'REAL', u'同业及其他金融机构存放款项', 'chart_line_value', u'万元'],
    ['xsck', 'REAL', u'吸收存款', 'chart_line_value', u'万元'],
    ['yfzgxc', 'REAL', u'应付职工薪酬', 'chart_line_value', u'万元'],
    ['yygj', 'REAL', u'盈余公积', 'chart_line_value', u'万元'],
    ['yqzc', 'REAL', u'油气资产', 'chart_line_value', u'万元'],
    ['ybfxzb', 'REAL', u'一般风险准备', 'chart_line_value', u'万元'],
    ['zzc', 'REAL', u'总资产', 'chart_line_value', u'万元'],
    # ['zczj', 'REAL', u'资产总计', 'chart_line_value', u'万元'],
    ['dqck', 'REAL', u'定期存款', 'chart_line_value', u'万元'],
    ['bhzydk', 'REAL', u'保户质押贷款', 'chart_line_value', u'万元'],
    ['ysbf', 'REAL', u'应收保费', 'chart_line_value', u'万元'],
    ['yysbf', 'REAL', u'预收保费', 'chart_line_value', u'万元'],
    ['dlzhzc', 'REAL', u'独立账户资产', 'chart_line_value', u'万元'],
    ['qtzc', 'REAL', u'其他资产', 'chart_line_value', u'万元'],
    ['zfz', 'REAL', u'总负债', 'chart_line_value', u'万元'],
    ['yfsxfjyj', 'REAL', u'应付手续费及佣金', 'chart_line_value', u'万元'],
    ['yfpfk', 'REAL', u'应付赔付款', 'chart_line_value', u'万元'],
    ['yfbdhl', 'REAL', u'应付保单红利', 'chart_line_value', u'万元'],
    ['dlzhfz', 'REAL', u'独立账户负债', 'chart_line_value', u'万元'],
    ['zbgj', 'REAL', u'资本公积', 'chart_line_value', u'万元'],
    ['khzcck', 'REAL', u'客户资金存款', 'chart_line_value', u'万元'],
    ['jyxwf', 'REAL', u'交易席位费', 'chart_line_value', u'万元'],
    ['kcsjrzc', 'REAL', u'可出售金融资产', 'chart_line_value', u'万元'],
    ['dlmmzqk', 'REAL', u'代理买卖证券款', 'chart_line_value', u'万元'],
    ['qtfz', 'REAL', u'其他负债', 'chart_line_value', u'万元'],
    ['dlcxzqk', 'REAL', u'代理承销证券款', 'chart_line_value', u'万元'],

]
